package exceptiondemos;

public class ArrayIndexOutofBoundException {
	public static void main(String args[]) {
		try {
		int numbers[]= {1,2,3};
		int element=numbers[1];
		System.out.println(element);
		
	}
		catch(Exception e)
		{
			System.out.println("exception caught");
			
		}
			
		}

}
